# Generated by Django 3.0.7 on 2020-07-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=12)),
                ('content', models.TextField()),
                ('DateTime', models.DateTimeField(blank=True)),
            ],
        ),
    ]
