# Generated by Django 3.0.7 on 2020-07-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='DateTime',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=' ', max_length=130),
            preserve_default=False,
        ),
    ]
